[project]
name = "ampgpt2-amp-challenge-2027"
version = "0.1.0"
description = "Entry submission for the AMP Challenge 2027"
readme = "README.md"
authors = [
    { name = "Sandra Clemens", email = "sandra.clemens@uni-muenster.de" }
]
requires-python = ">=3.10,<=3.14"
dependencies = [
    "biopython>=1.88",
    "levenshtein>=0.27.4",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "torch>=2.5.1",
    "tqdm>=4.70.1",
    "transformers>=5.17.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu121" }

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true


[project.scripts]
generate = "ampgpt2_amp_challenge_2027.generate:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
