"""
APEX-based antibacterial activity scoring based on the diffusion starter kit.

APEX is executed as an isolated subprocess using its own environment. The
11 pathogen-specific predictions are summarized as the mean predicted MIC for
candidate ranking and library enrichment.
"""
from __future__ import annotations

from pathlib import Path
import subprocess
import tempfile
import os

import pandas as pd
ROOT = Path(__file__).resolve().parents[2]
APEX_DIR = ROOT / "apex"

APEX_PANEL = [
    "A. baumannii ATCC 19606",
    "E. coli ATCC 11775",
    "E. coli AIC221",
    "E. coli AIC222",
    "K. pneumoniae ATCC 13883",
    "P. aeruginosa PA01",
    "P. aeruginosa PA14",
    "S. aureus ATCC 12600",
    "S. aureus (ATCC BAA-1556) - MRSA",
    "vancomycin-resistant E. faecalis ATCC 700802",
    "vancomycin-resistant E. faecium ATCC 700221",
]

def score_apex(
    sequences: list[str],
    *,
    gpu: bool = False,
) -> pd.DataFrame:
    """
    Run APEX as isolated subprocess

    Returns one row per input sequence and adds:
        sequence
        mean_mic
    plus all pathogen-specific MIC columns generated by APEX.
    """
    from ampgpt2_amp_challenge_2027.generate import write_fasta

    if not sequences:
        return pd.DataFrame()

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        fasta = tmp / "candidates.fasta"

        write_fasta(sequences, fasta, "tmp")

        # APEX writes Predicted_MICs.csv into its current directory.
        output_csv = APEX_DIR / "Predicted_MICs.csv"

        if output_csv.exists():
            output_csv.unlink()
            
        env = os.environ.copy()
        env.pop("LD_LIBRARY_PATH", None)

        subprocess.run(
            [
                "uv",
                "run",
                "--project",
                str(APEX_DIR),
                "python",
                "APEX_predict.py",
                "-i",
                str(fasta.resolve()),
                "-g",
                "1" if gpu else "0",
            ],
            cwd=APEX_DIR,
            env=env,
            check=True,
        )

        if not output_csv.exists():
            raise RuntimeError(
                "APEX completed but apex/Predicted_MICs.csv was not produced"
            )

        df = pd.read_csv(output_csv, index_col=0)

    if len(df) != len(sequences):
        raise RuntimeError(
            f"APEX returned {len(df)} rows for {len(sequences)} sequences"
        )

    df = df.reset_index(drop=True)
    df.insert(0, "sequence", sequences)

    mic_columns = [
        c for c in df.columns
        if c != "sequence" and pd.api.types.is_numeric_dtype(df[c])
    ]

    if not mic_columns:
        raise RuntimeError("No numeric MIC columns found in APEX output")

    df["mean_mic"] = df[mic_columns].mean(axis=1)

    return df